import { debounceTime, fromEvent, map, mergeAll, mergeMap, Observable, switchMap } from "rxjs";
import { ajax } from "rxjs/ajax";
import { GitHubUsers, Item } from "../interfaces/Git_Hub_Users";





// Generated by https://quicktype.io


const body = document.querySelector('body');
const textInput = document.createElement('input');
const orderList = document.createElement('ol');
body.append(textInput, orderList);

const input$ = fromEvent<KeyboardEvent>(textInput, 'input');

const showuser = (users: Item[]) => {

    orderList.innerHTML = '';

    for (const user of users) {
        const li = document.createElement('li');
        const img = document.createElement('img');
        img.src = user.avatar_url;

        const anchor = document.createElement('a');
        anchor.href = user.html_url;
        anchor.text = 'Ver página';
        anchor.target = '_blank';
        li.append(img);
        li.append(user.login + ' ');
        li.append(anchor);

        orderList.append(li);
    }

}

input$
    .pipe(
        debounceTime(500),
        mergeMap<KeyboardEvent, Observable<GitHubUsers>>((event) => {
            const text = event.target['value'];
            /**
             * We can use the ajax function to make a request to an API
             * and get the response. that response is an observable
             * that we can subscribe to.
             */
            return ajax.getJSON(`https://api.github.com/search/users?q=${text}`);
        }
        ),

        /**
         * The map operator is used to get the items property of the response
         * object. This property contains the array of users that we want to
         * display.
         */
        map((response) => response.items),
    )
    .subscribe({
        next: (response) => {
            showuser(response);
        }
    });


const url = 'https://httpbin.org/delay/1?arg=';
input$
    .pipe(
        /**
         * el problema de mergeMap es que si se hace una petición y se hace otra antes de que la primera termine
         * se cancela la primera y se hace la segunda
         *  asi que mergeMap no es la mejor opción para hacer peticiones http
         */
        switchMap<KeyboardEvent, Observable<any>>((event) => {
            return ajax.getJSON(url + event.target['value']);
        }
        )
    )
    .subscribe({
        next: (response) => {
            console.log(response);
        }
    });